spring:
  datasource:
    url: jdbc:mysql://hostname:3306/databaseName?useUnicode=true&characterEncoding=utf8&nullNamePatternMatchesAll=true
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true